---
- name: Deploy Ghost
  kubernetes.core.k8s:
    state: present
    definition: 
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ghost-deployment
        namespace: "{{ namespace }}"
        labels: 
          app: ghost
      spec:
        replicas: 1
        selector: 
          matchLabels:
            app: ghost
        strategy: 
          type: Recreate
        template:
          metadata:
            labels:
              app: ghost
          spec:
            containers:
              - name: ghost
                image: "{{ ghost_image }}"
                env:
                - name: database__connection__host
                  value: "{{ database_service }}"
                  url: http://localhost:3306
                - name: database__connection__database
                  value: "{{ database_name }}"
                - name: database__connection__user
                  value: "{{ database_user }}"
                - name: database__connection__password
                  valueFrom:
                    secretKeyRef:
                      name: ghost-secret-data
                      key: password
                ports:
                  - containerPort: "{{ ghost_container_port }}"
                
- name: Create Ghost Service
  kubernetes.core.k8s:
    state: present
    definition:   
      apiVersion: v1
      kind: Service
      metadata: 
        name: ghost-service
        namespace: "{{ namespace }}"
        labels:
          app: ghost
      spec:
        type: LoadBalancer
        selector:
          app: ghost
        ports:
          - targetPort: "{{ ghost_container_port }}" # Port that containers are listening on
            port: "{{ ghost_port }}" # Port that's exposed internally in the cluster

# - name: Get MySQL pod name
#   kubernetes.core.k8s_info:
#     state: present
#     kind: pod
#     label_selectors:
#       - app = mysql
#   register: pods






# - name: get info
#   debug:
#     var: pods