---
# Persistent Volume Claim for MySQL pod
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
