---
# Deployment for MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-mysql-deployment
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env: # The variables below could be set on a ConfigMap object
        - name: MYSQL_DATABASE
          value: "{{ database_name }}"
        - name: MYSQL_USER
          value: "{{ database_user }}"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ghost-secret-data
              key: password

        ports:
        - containerPort: "{{ database_port }}"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
