---
# Service for exposing MySQL
apiVersion: v1
kind: Service
metadata:
  name: ghost-mysql-service # logical name of the service, which will also become the DNS name of the service when it is created.
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - targetPort: "{{ database_port }}" # port that containers are listening on
      port: "{{ database_port }}" # port number exposed internally in the cluster