---
- name: Delete Ghost deployment
  shell: kubectl delete deployment ghost-deployment
  ignore_errors: true
    
  
- name: Delete Ghost Service
  shell: kubectl delete service ghost-service
  ignore_errors: true

- name: Delete Ghost Dashboard 
  command: gcloud monitoring dashboards delete ghost_dashboard --quiet